server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

    # Excepción para robots.txt
    location = /robots.txt {
      try_files $uri =404;
      access_log off;
      log_not_found off;
    }


  location / {
    try_files $uri $uri/ /index.html;
  }

  # Página de error 404 personalizada
  error_page 404 /index.html;

  # Archivos estáticos
  location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|ttf|eot)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public";
  }
}
